# Generated by Django 4.1 on 2022-09-20 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='ChatName')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=20, unique=True, verbose_name='Login')),
                ('Password', models.CharField(max_length=64, verbose_name='Password')),
                ('Photo', models.ImageField(upload_to='photos/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Private_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(max_length=250, verbose_name='Message')),
                ('Date_Time', models.DateTimeField(auto_now_add=True, verbose_name='Date_Time')),
                ('From_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From_User', to='Messenger.users', verbose_name='From_User')),
                ('To_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To_User', to='Messenger.users', verbose_name='To User')),
            ],
            options={
                'verbose_name': 'Private Log',
                'verbose_name_plural': 'Private Logs',
            },
        ),
        migrations.CreateModel(
            name='ChatsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField(max_length=250, verbose_name='Message')),
                ('User_Name', models.CharField(max_length=20, verbose_name='User_Name')),
                ('Date_Time', models.DateTimeField(auto_now_add=True, verbose_name='Date_Time')),
                ('Chat_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messenger.chats', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'Chat Log',
                'verbose_name_plural': 'Chats Logs',
            },
        ),
        migrations.AddField(
            model_name='chats',
            name='Admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Messenger.users', verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='chats',
            name='UserS',
            field=models.ManyToManyField(related_name='Chat_Users', to='Messenger.users', verbose_name='Users'),
        ),
    ]
