# Generated by Django 4.1 on 2022-09-20 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Messenger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Login',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Password',
        ),
        migrations.AddField(
            model_name='users',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chats',
            name='Admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='UserS',
            field=models.ManyToManyField(related_name='Chat_Users', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='private_log',
            name='From_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From_User', to=settings.AUTH_USER_MODEL, verbose_name='From_User'),
        ),
        migrations.AlterField(
            model_name='private_log',
            name='To_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To_User', to=settings.AUTH_USER_MODEL, verbose_name='To User'),
        ),
    ]
