# Generated by Django 4.1.1 on 2022-09-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0003_alter_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Photo'),
        ),
    ]
