# Generated by Django 4.1.2 on 2022-10-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0004_alter_users_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Friends',
            field=models.ManyToManyField(blank=True, to='Messenger.users'),
        ),
    ]
