# Generated by Django 4.2.2 on 2023-07-10 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Messenger', '0008_remove_chatslog_chat_name_delete_chats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_log',
            name='To_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To_User', to=settings.AUTH_USER_MODEL, verbose_name='To_User'),
        ),
    ]
